# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' forward_backward_
#'
#' Carry out the forward-backward algorithm for the HMM implied by knowing the two
#' parental haplotypes.
#'
#' @param x  0-1 vector of length p giving the offspring haplotypes
#' @param p1 0-1 vector of length p giving one parental haplotype
#' @param p2 0-1 vector of length p giving the other parental haplotype
#' @param d numberic vector of length p - 1  giving the distance between each site
#' @param p length of the vector x
#' @param lambda the recombination rate, a multiplier for the distance d
#' @param epsilon the pointwise mutation rate
#' @param start indexes of the subset of x to perform the computation (1 indexed)
#' @param end indexes of the subset of x to perform the computation (1 indexed)
#'
#' @return p1_start: the probability that the latent state immediately before the specified window is 1,
#'        i.e. the offspring is being copied from p1.
#' @return p1_start_odd: probability of an odd number of recombinations given that 
#'       the latent state immediately before the specified window is 1.
#' @return  p2_start_odd: probability of an odd number of recombinations given that 
#'       the latent state immediately before the specified window is 2.
forward_backward_ <- function(x, p1, p2, d, p, lambda, epsilon, start, end) {
    .Call('_digitaltwins_forward_backward_', PACKAGE = 'digitaltwins', x, p1, p2, d, p, lambda, epsilon, start, end)
}

#'sample_ancestry_
#'
#' Sample the latent state of ancenstry indicators for a haplotype given
#'   its two ancestral haplotypes.
#'
#' @param x 0-1 vector of length p giving the offspring haplotypes
#' @param p1 0-1 vector of length p giving one parental haplotype
#' @param p2 0-1 vector of length p giving the other parental haplotype
#' @param d numberic vector of length p - 1  giving the distance between each site
#' @param p length of the vector x
#' @param lambda the recombination rate, a multiplier for the distance d
#' @param epsilon the pointwise mutation rate
#'
#' @return a vector of of the ancestral states
sample_ancestry_ <- function(x, p1, p2, d, p, lambda, epsilon) {
    .Call('_digitaltwins_sample_ancestry_', PACKAGE = 'digitaltwins', x, p1, p2, d, p, lambda, epsilon)
}

